# Generated by Django 5.2.7 on 2025-10-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargoEmpleados',
            fields=[
                ('id_cargo_emp', models.AutoField(primary_key=True, serialize=False)),
                ('carg_nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'cargo_empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaPlatos',
            fields=[
                ('id_categoria_plato', models.AutoField(primary_key=True, serialize=False)),
                ('catplt_nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'categoria_platos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProveedores',
            fields=[
                ('id_categoria_prov', models.AutoField(primary_key=True, serialize=False)),
                ('catprov_nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'categoria_proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=120)),
                ('cli_tel', models.CharField(blank=True, max_length=30, null=True)),
                ('cli_correo', models.CharField(blank=True, max_length=120, null=True)),
                ('cli_dni', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('com_fecha_hora', models.DateTimeField()),
                ('com_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('com_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('detcom_cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('detcom_precio_uni', models.DecimalField(decimal_places=3, max_digits=12)),
                ('detcom_subtotal', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('detped_cantidad', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'detalle_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleRecetas',
            fields=[
                ('id_detalle_receta', models.AutoField(primary_key=True, serialize=False)),
                ('detr_cant_unid', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
            options={
                'db_table': 'detalle_recetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('detven_precio_uni', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detven_cantidad', models.PositiveIntegerField()),
                ('detven_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'detalle_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=80)),
                ('emp_apellido', models.CharField(max_length=80)),
                ('emp_tel', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_correo', models.CharField(blank=True, max_length=120, null=True)),
                ('emp_dni', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id_estado_compra', models.AutoField(primary_key=True, serialize=False)),
                ('estcom_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEmpleados',
            fields=[
                ('id_estado_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('estemp_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoInsumos',
            fields=[
                ('id_estado_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('estins_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedidos',
            fields=[
                ('id_estado_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estped_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPlatos',
            fields=[
                ('id_estado_plato', models.AutoField(primary_key=True, serialize=False)),
                ('estplt_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_platos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProveedores',
            fields=[
                ('id_estado_prov', models.AutoField(primary_key=True, serialize=False)),
                ('estprov_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoVentas',
            fields=[
                ('id_estado_venta', models.AutoField(primary_key=True, serialize=False)),
                ('estven_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('ins_nombre', models.CharField(max_length=120, unique=True)),
                ('ins_unidad', models.CharField(max_length=20)),
                ('ins_stock_actual', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ins_punto_reposicion', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ins_stock_min', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ins_stock_max', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('ms_numero', models.PositiveIntegerField(unique=True)),
                ('ms_disponible', models.IntegerField()),
            ],
            options={
                'db_table': 'mesas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metpag_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'metodo_de_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('mv_fecha_hora', models.DateTimeField()),
                ('mv_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mv_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'movimientos_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('ped_fecha_hora_ini', models.DateTimeField()),
                ('ped_fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('ped_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('plt_nombre', models.CharField(max_length=120, unique=True)),
                ('plt_precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plt_stock', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'platos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.CharField(max_length=120, unique=True)),
                ('prov_tel', models.CharField(blank=True, max_length=30, null=True)),
                ('prov_correo', models.CharField(blank=True, max_length=120, null=True)),
                ('prov_direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedoresXInsumos',
            fields=[
                ('id_prov_x_ins', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proveedores_x_insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('rec_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'recetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoCaja',
            fields=[
                ('id_tipo_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('tmovc_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_movimiento_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPedidos',
            fields=[
                ('id_tipo_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('tipped_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('ven_fecha_hora', models.DateTimeField()),
                ('ven_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ven_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoReceta',
            fields=[
                ('id_estado_receta', models.AutoField(primary_key=True, serialize=False)),
                ('estrec_nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Receta',
                'verbose_name_plural': 'Estados de Receta',
                'db_table': 'estado_receta',
            },
        ),
    ]
