# Generated by Django 5.2.7 on 2025-10-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_mesas',
            fields=[
                ('id_estado_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('estms_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Mesa',
                'verbose_name_plural': 'Estados de Mesa',
                'db_table': 'estado_mesas',
            },
        ),
        migrations.AlterModelOptions(
            name='mesas',
            options={},
        ),
    ]
