# Generated by Django 5.2.7 on 2025-10-28 10:27

from django.db import migrations, models
from django.core.validators import MinValueValidator

class Migration(migrations.Migration):

    dependencies = [
        # 👇 Poné aquí tu última migración APLICADA en pizzeria
        ("pizzeria", "0004_add_precio_unitario_pxi"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 1) Operación real en la base (MySQL)
            database_operations=[
                migrations.RunSQL(
                    # forward SQL
                    sql=(
                        "ALTER TABLE proveedores_x_insumos "
                        "ADD COLUMN precio_unitario DECIMAL(12,3) NULL;"
                    ),
                    # reverse SQL (por si alguna vez hacés migrate --rollback)
                    reverse_sql=(
                        "ALTER TABLE proveedores_x_insumos "
                        "DROP COLUMN precio_unitario;"
                    ),
                ),
            ],
            # 2) Operación de estado de Django (para que el ORM conozca el campo)
            state_operations=[
                migrations.AddField(
                    model_name="proveedoresxinsumos",  # en minúsculas
                    name="precio_unitario",
                    field=models.DecimalField(
                        max_digits=12,
                        decimal_places=3,   # ← usás 3 decimales en tu modelo
                        null=True, blank=True,
                        validators=[MinValueValidator(0)],
                        help_text="Precio unitario acordado para este insumo con el proveedor.",
                    ),
                ),
            ],
        ),
    ]

