# Generated by Django 5.2.7 on 2025-10-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_add_precio_unitario_unmanaged'),
    ]

    operations = [
    ]
