# Generated by Django 5.2.7 on 2025-11-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0008_metodo_pago_model_and_fks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estado_mesas',
        ),
        migrations.AlterModelOptions(
            name='mesas',
            options={'managed': False},
        ),
    ]
